- name: yum install epel
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: latest
  tags: sl

- name: yum install sl
  yum:
    name: sl
    state: latest
    enablerepo: epel
  tags: sl

- name: send .bashrc
  copy:
    src: .bashrc
    dest: /home/ec2-user/.bashrc
    mode: '0644'
    owner: ec2-user
    group: ec2-user
    backup: yes
  notify: reflect .bashrc
  tags: sl