---
- hosts: webserver
  become: yes
  tasks:
  - name: yum install httpd
    yum:
      name: httpd
      state: latest

  - name: httpd enable
    systemd:
      name: httpd
      state: started
      enabled: yes